/*
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kr.appkr.swagger_poc_api.service;

import kr.appkr.swagger_poc_api.ApiException;
import kr.appkr.swagger_poc_api.model.AccessToken;
import kr.appkr.swagger_poc_api.model.ErrorDto;
import kr.appkr.swagger_poc_api.model.LoginRequest;
import kr.appkr.swagger_poc_api.model.UserDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
@Ignore
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    
    /**
     * 로그인합니다.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        LoginRequest body = null;
        AccessToken response = api.login(body);

        // TODO: test validations
    }
    
    /**
     * 로그아웃합니다.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logoutTest() throws ApiException {
        String authorization = null;
        api.logout(authorization);

        // TODO: test validations
    }
    
    /**
     * 프로필 정보를 확인합니다.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void meTest() throws ApiException {
        String authorization = null;
        UserDto response = api.me(authorization);

        // TODO: test validations
    }
    
    /**
     * 로그인합니다.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void refreshTokenTest() throws ApiException {
        String authorization = null;
        AccessToken response = api.refreshToken(authorization);

        // TODO: test validations
    }
    
}
