<?php
/**
 * ReviewApi
 * PHP version 5
 *
 * @category Class
 * @package  Appkr\SwaggerPocApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DB-LOCK-POC
 *
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Appkr\SwaggerPocApi\Service;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Appkr\SwaggerPocApi\ApiException;
use Appkr\SwaggerPocApi\Configuration;
use Appkr\SwaggerPocApi\HeaderSelector;
use Appkr\SwaggerPocApi\ObjectSerializer;

/**
 * ReviewApi Class Doc Comment
 *
 * @category Class
 * @package  Appkr\SwaggerPocApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReviewApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createReview
     *
     * 새 리뷰를 등록합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId productId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body body (required)
     *
     * @throws \Appkr\SwaggerPocApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Appkr\SwaggerPocApi\Model\ReviewDto
     */
    public function createReview($authorization, $productId, $body)
    {
        list($response) = $this->createReviewWithHttpInfo($authorization, $productId, $body);
        return $response;
    }

    /**
     * Operation createReviewWithHttpInfo
     *
     * 새 리뷰를 등록합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body (required)
     *
     * @throws \Appkr\SwaggerPocApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Appkr\SwaggerPocApi\Model\ReviewDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function createReviewWithHttpInfo($authorization, $productId, $body)
    {
        $returnType = '\Appkr\SwaggerPocApi\Model\ReviewDto';
        $request = $this->createReviewRequest($authorization, $productId, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Appkr\SwaggerPocApi\Model\ReviewDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Appkr\SwaggerPocApi\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createReviewAsync
     *
     * 새 리뷰를 등록합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createReviewAsync($authorization, $productId, $body)
    {
        return $this->createReviewAsyncWithHttpInfo($authorization, $productId, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createReviewAsyncWithHttpInfo
     *
     * 새 리뷰를 등록합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createReviewAsyncWithHttpInfo($authorization, $productId, $body)
    {
        $returnType = '\Appkr\SwaggerPocApi\Model\ReviewDto';
        $request = $this->createReviewRequest($authorization, $productId, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createReview'
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createReviewRequest($authorization, $productId, $body)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling createReview'
            );
        }
        // verify the required parameter 'productId' is set
        if ($productId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $productId when calling createReview'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createReview'
            );
        }

        $resourcePath = '/v1/products/{productId}/reviews';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($productId !== null) {
            $resourcePath = str_replace(
                '{' . 'productId' . '}',
                ObjectSerializer::toPathValue($productId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteReview
     *
     * 리뷰를 삭제합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId productId (required)
     * @param  int $reviewId reviewId (required)
     *
     * @throws \Appkr\SwaggerPocApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteReview($authorization, $productId, $reviewId)
    {
        $this->deleteReviewWithHttpInfo($authorization, $productId, $reviewId);
    }

    /**
     * Operation deleteReviewWithHttpInfo
     *
     * 리뷰를 삭제합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  int $reviewId (required)
     *
     * @throws \Appkr\SwaggerPocApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteReviewWithHttpInfo($authorization, $productId, $reviewId)
    {
        $returnType = '';
        $request = $this->deleteReviewRequest($authorization, $productId, $reviewId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Appkr\SwaggerPocApi\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteReviewAsync
     *
     * 리뷰를 삭제합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  int $reviewId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteReviewAsync($authorization, $productId, $reviewId)
    {
        return $this->deleteReviewAsyncWithHttpInfo($authorization, $productId, $reviewId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteReviewAsyncWithHttpInfo
     *
     * 리뷰를 삭제합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  int $reviewId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteReviewAsyncWithHttpInfo($authorization, $productId, $reviewId)
    {
        $returnType = '';
        $request = $this->deleteReviewRequest($authorization, $productId, $reviewId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteReview'
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  int $reviewId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteReviewRequest($authorization, $productId, $reviewId)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling deleteReview'
            );
        }
        // verify the required parameter 'productId' is set
        if ($productId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $productId when calling deleteReview'
            );
        }
        // verify the required parameter 'reviewId' is set
        if ($reviewId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $reviewId when calling deleteReview'
            );
        }

        $resourcePath = '/v1/products/{productId}/reviews/{reviewId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($productId !== null) {
            $resourcePath = str_replace(
                '{' . 'productId' . '}',
                ObjectSerializer::toPathValue($productId),
                $resourcePath
            );
        }
        // path params
        if ($reviewId !== null) {
            $resourcePath = str_replace(
                '{' . 'reviewId' . '}',
                ObjectSerializer::toPathValue($reviewId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listReviews
     *
     * 상품에 대한 리뷰 목록을 조회합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId productId (required)
     * @param  string $q 검색어 (optional)
     * @param  int $userId 작성자 ID (optional)
     * @param  string $sortKey 정렬 필드 (optional, default to CREATED_AT)
     * @param  string $sortDirection 정렬 방향 (optional, default to DESC)
     * @param  int $page 페이지 (optional, default to 1)
     * @param  int $size 페이지당 표시할 아이템 개수 (optional, default to 10)
     *
     * @throws \Appkr\SwaggerPocApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Appkr\SwaggerPocApi\Model\ReviewListResponse
     */
    public function listReviews($authorization, $productId, $q = null, $userId = null, $sortKey = 'CREATED_AT', $sortDirection = 'DESC', $page = '1', $size = '10')
    {
        list($response) = $this->listReviewsWithHttpInfo($authorization, $productId, $q, $userId, $sortKey, $sortDirection, $page, $size);
        return $response;
    }

    /**
     * Operation listReviewsWithHttpInfo
     *
     * 상품에 대한 리뷰 목록을 조회합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  string $q 검색어 (optional)
     * @param  int $userId 작성자 ID (optional)
     * @param  string $sortKey 정렬 필드 (optional, default to CREATED_AT)
     * @param  string $sortDirection 정렬 방향 (optional, default to DESC)
     * @param  int $page 페이지 (optional, default to 1)
     * @param  int $size 페이지당 표시할 아이템 개수 (optional, default to 10)
     *
     * @throws \Appkr\SwaggerPocApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Appkr\SwaggerPocApi\Model\ReviewListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listReviewsWithHttpInfo($authorization, $productId, $q = null, $userId = null, $sortKey = 'CREATED_AT', $sortDirection = 'DESC', $page = '1', $size = '10')
    {
        $returnType = '\Appkr\SwaggerPocApi\Model\ReviewListResponse';
        $request = $this->listReviewsRequest($authorization, $productId, $q, $userId, $sortKey, $sortDirection, $page, $size);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Appkr\SwaggerPocApi\Model\ReviewListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Appkr\SwaggerPocApi\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listReviewsAsync
     *
     * 상품에 대한 리뷰 목록을 조회합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  string $q 검색어 (optional)
     * @param  int $userId 작성자 ID (optional)
     * @param  string $sortKey 정렬 필드 (optional, default to CREATED_AT)
     * @param  string $sortDirection 정렬 방향 (optional, default to DESC)
     * @param  int $page 페이지 (optional, default to 1)
     * @param  int $size 페이지당 표시할 아이템 개수 (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listReviewsAsync($authorization, $productId, $q = null, $userId = null, $sortKey = 'CREATED_AT', $sortDirection = 'DESC', $page = '1', $size = '10')
    {
        return $this->listReviewsAsyncWithHttpInfo($authorization, $productId, $q, $userId, $sortKey, $sortDirection, $page, $size)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listReviewsAsyncWithHttpInfo
     *
     * 상품에 대한 리뷰 목록을 조회합니다.
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  string $q 검색어 (optional)
     * @param  int $userId 작성자 ID (optional)
     * @param  string $sortKey 정렬 필드 (optional, default to CREATED_AT)
     * @param  string $sortDirection 정렬 방향 (optional, default to DESC)
     * @param  int $page 페이지 (optional, default to 1)
     * @param  int $size 페이지당 표시할 아이템 개수 (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listReviewsAsyncWithHttpInfo($authorization, $productId, $q = null, $userId = null, $sortKey = 'CREATED_AT', $sortDirection = 'DESC', $page = '1', $size = '10')
    {
        $returnType = '\Appkr\SwaggerPocApi\Model\ReviewListResponse';
        $request = $this->listReviewsRequest($authorization, $productId, $q, $userId, $sortKey, $sortDirection, $page, $size);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listReviews'
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  string $q 검색어 (optional)
     * @param  int $userId 작성자 ID (optional)
     * @param  string $sortKey 정렬 필드 (optional, default to CREATED_AT)
     * @param  string $sortDirection 정렬 방향 (optional, default to DESC)
     * @param  int $page 페이지 (optional, default to 1)
     * @param  int $size 페이지당 표시할 아이템 개수 (optional, default to 10)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listReviewsRequest($authorization, $productId, $q = null, $userId = null, $sortKey = 'CREATED_AT', $sortDirection = 'DESC', $page = '1', $size = '10')
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling listReviews'
            );
        }
        // verify the required parameter 'productId' is set
        if ($productId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $productId when calling listReviews'
            );
        }

        $resourcePath = '/v1/products/{productId}/reviews';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($q !== null) {
            $queryParams['q'] = ObjectSerializer::toQueryValue($q);
        }
        // query params
        if ($userId !== null) {
            $queryParams['user_id'] = ObjectSerializer::toQueryValue($userId);
        }
        // query params
        if ($sortKey !== null) {
            $queryParams['sort_key'] = ObjectSerializer::toQueryValue($sortKey);
        }
        // query params
        if ($sortDirection !== null) {
            $queryParams['sort_direction'] = ObjectSerializer::toQueryValue($sortDirection);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }
        // query params
        if ($size !== null) {
            $queryParams['size'] = ObjectSerializer::toQueryValue($size);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($productId !== null) {
            $resourcePath = str_replace(
                '{' . 'productId' . '}',
                ObjectSerializer::toPathValue($productId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateReview
     *
     * 리뷰를 수정합니다 (ON PURPOSE 10 SEC DELAY TO TEST PESSIMISTIC/OPTIMISTIC DB LOCK).
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId productId (required)
     * @param  int $reviewId reviewId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body body (optional)
     *
     * @throws \Appkr\SwaggerPocApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Appkr\SwaggerPocApi\Model\ReviewDto
     */
    public function updateReview($authorization, $productId, $reviewId, $body = null)
    {
        list($response) = $this->updateReviewWithHttpInfo($authorization, $productId, $reviewId, $body);
        return $response;
    }

    /**
     * Operation updateReviewWithHttpInfo
     *
     * 리뷰를 수정합니다 (ON PURPOSE 10 SEC DELAY TO TEST PESSIMISTIC/OPTIMISTIC DB LOCK).
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  int $reviewId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body (optional)
     *
     * @throws \Appkr\SwaggerPocApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Appkr\SwaggerPocApi\Model\ReviewDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateReviewWithHttpInfo($authorization, $productId, $reviewId, $body = null)
    {
        $returnType = '\Appkr\SwaggerPocApi\Model\ReviewDto';
        $request = $this->updateReviewRequest($authorization, $productId, $reviewId, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Appkr\SwaggerPocApi\Model\ReviewDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Appkr\SwaggerPocApi\Model\ErrorDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateReviewAsync
     *
     * 리뷰를 수정합니다 (ON PURPOSE 10 SEC DELAY TO TEST PESSIMISTIC/OPTIMISTIC DB LOCK).
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  int $reviewId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateReviewAsync($authorization, $productId, $reviewId, $body = null)
    {
        return $this->updateReviewAsyncWithHttpInfo($authorization, $productId, $reviewId, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateReviewAsyncWithHttpInfo
     *
     * 리뷰를 수정합니다 (ON PURPOSE 10 SEC DELAY TO TEST PESSIMISTIC/OPTIMISTIC DB LOCK).
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  int $reviewId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateReviewAsyncWithHttpInfo($authorization, $productId, $reviewId, $body = null)
    {
        $returnType = '\Appkr\SwaggerPocApi\Model\ReviewDto';
        $request = $this->updateReviewRequest($authorization, $productId, $reviewId, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateReview'
     *
     * @param  string $authorization 액세스 토큰 (required)
     * @param  int $productId (required)
     * @param  int $reviewId (required)
     * @param  \Appkr\SwaggerPocApi\Model\NewReviewRequest $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateReviewRequest($authorization, $productId, $reviewId, $body = null)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling updateReview'
            );
        }
        // verify the required parameter 'productId' is set
        if ($productId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $productId when calling updateReview'
            );
        }
        // verify the required parameter 'reviewId' is set
        if ($reviewId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $reviewId when calling updateReview'
            );
        }

        $resourcePath = '/v1/products/{productId}/reviews/{reviewId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($productId !== null) {
            $resourcePath = str_replace(
                '{' . 'productId' . '}',
                ObjectSerializer::toPathValue($productId),
                $resourcePath
            );
        }
        // path params
        if ($reviewId !== null) {
            $resourcePath = str_replace(
                '{' . 'reviewId' . '}',
                ObjectSerializer::toPathValue($reviewId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
