/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Paginator from './Paginator';





/**
* The Meta model module.
* @module model/Meta
* @version 1
*/
export default class Meta {
    /**
    * Constructs a new <code>Meta</code>.
    * @alias module:model/Meta
    * @class
    * @param pagination {module:model/Paginator} 
    */

    constructor(pagination) {
        

        
        

        this['pagination'] = pagination;

        
    }

    /**
    * Constructs a <code>Meta</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Meta} obj Optional instance to populate.
    * @return {module:model/Meta} The populated <code>Meta</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Meta();

            
            
            

            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Paginator.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Paginator} pagination
    */
    pagination = undefined;








}


