/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The NewReviewRequest model module.
* @module model/NewReviewRequest
* @version 1
*/
export default class NewReviewRequest {
    /**
    * Constructs a new <code>NewReviewRequest</code>.
    * @alias module:model/NewReviewRequest
    * @class
    * @param title {String} 제목
    * @param content {String} 본문
    */

    constructor(title, content) {
        

        
        

        this['title'] = title;this['content'] = content;

        
    }

    /**
    * Constructs a <code>NewReviewRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NewReviewRequest} obj Optional instance to populate.
    * @return {module:model/NewReviewRequest} The populated <code>NewReviewRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewReviewRequest();

            
            
            

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }

    /**
    * 제목
    * @member {String} title
    */
    title = undefined;
    /**
    * 본문
    * @member {String} content
    */
    content = undefined;








}


