/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PaginatorLink model module.
* @module model/PaginatorLink
* @version 1
*/
export default class PaginatorLink {
    /**
    * Constructs a new <code>PaginatorLink</code>.
    * @alias module:model/PaginatorLink
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PaginatorLink</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaginatorLink} obj Optional instance to populate.
    * @return {module:model/PaginatorLink} The populated <code>PaginatorLink</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginatorLink();

            
            
            

            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
        }
        return obj;
    }

    /**
    * 다음 페이지
    * @member {String} previous
    */
    previous = undefined;
    /**
    * 이전 페이지
    * @member {String} next
    */
    next = undefined;








}


