/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NewReviewRequest from './NewReviewRequest';
import ProductDto from './ProductDto';
import Timestamp from './Timestamp';
import UserDto from './UserDto';





/**
* The ReviewDto model module.
* @module model/ReviewDto
* @version 1
*/
export default class ReviewDto {
    /**
    * Constructs a new <code>ReviewDto</code>.
    * @alias module:model/ReviewDto
    * @class
    * @implements module:model/NewReviewRequest
    * @implements module:model/Timestamp
    * @param title {String} 제목
    * @param content {String} 본문
    */

    constructor(title, content) {
        

        
        NewReviewRequest.call(this, title, content);Timestamp.call(this);

        

        
    }

    /**
    * Constructs a <code>ReviewDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ReviewDto} obj Optional instance to populate.
    * @return {module:model/ReviewDto} The populated <code>ReviewDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReviewDto();

            
            
            NewReviewRequest.constructFromObject(data, obj);Timestamp.constructFromObject(data, obj);

            if (data.hasOwnProperty('author')) {
                obj['author'] = UserDto.constructFromObject(data['author']);
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ProductDto.constructFromObject(data['product']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UserDto} author
    */
    author = undefined;
    /**
    * @member {module:model/ProductDto} product
    */
    product = undefined;


    // Implement NewReviewRequest interface:
    /**
    * 제목
    * @member {String} title
    */
    title = undefined;
/**
    * 본문
    * @member {String} content
    */
    content = undefined;

    // Implement Timestamp interface:
    /**
    * 최초 생성 시각
    * @member {String} created_at
    */
    created_at = undefined;
/**
    * 최종 수정 시각
    * @member {String} updated_at
    */
    updated_at = undefined;







}


