/*
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kr.appkr.swagger_poc_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NewProductRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-23T00:35:43.003+09:00")
public class NewProductRequest {
  @SerializedName("title")
  private String title = null;

  @SerializedName("stock")
  private Integer stock = null;

  @SerializedName("price")
  private Long price = null;

  @SerializedName("description")
  private String description = null;

  public NewProductRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * 상품명
   * @return title
  **/
  @ApiModelProperty(example = "[특가] 반짝반짝 빛나는 에폭시 스티커", required = true, value = "상품명")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public NewProductRequest stock(Integer stock) {
    this.stock = stock;
    return this;
  }

   /**
   * 재고수량
   * @return stock
  **/
  @ApiModelProperty(example = "100", required = true, value = "재고수량")
  public Integer getStock() {
    return stock;
  }

  public void setStock(Integer stock) {
    this.stock = stock;
  }

  public NewProductRequest price(Long price) {
    this.price = price;
    return this;
  }

   /**
   * 가격
   * @return price
  **/
  @ApiModelProperty(example = "1600", required = true, value = "가격")
  public Long getPrice() {
    return price;
  }

  public void setPrice(Long price) {
    this.price = price;
  }

  public NewProductRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 상품 설명
   * @return description
  **/
  @ApiModelProperty(example = "라이언 캐릭터를 주제로 한 투명 에폭시 스티커..", required = true, value = "상품 설명")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewProductRequest newProductRequest = (NewProductRequest) o;
    return Objects.equals(this.title, newProductRequest.title) &&
        Objects.equals(this.stock, newProductRequest.stock) &&
        Objects.equals(this.price, newProductRequest.price) &&
        Objects.equals(this.description, newProductRequest.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, stock, price, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewProductRequest {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    stock: ").append(toIndentedString(stock)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

