/*
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kr.appkr.swagger_poc_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import kr.appkr.swagger_poc_api.model.NewReviewRequest;
import kr.appkr.swagger_poc_api.model.ProductDto;
import kr.appkr.swagger_poc_api.model.UserDto;

/**
 * ReviewDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-22T15:22:50.443+09:00")
public class ReviewDto {
  @SerializedName("title")
  private String title = null;

  @SerializedName("content")
  private String content = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  @SerializedName("author")
  private UserDto author = null;

  @SerializedName("product")
  private ProductDto product = null;

  public ReviewDto title(String title) {
    this.title = title;
    return this;
  }

   /**
   * 제목
   * @return title
  **/
  @ApiModelProperty(example = "접착력이 약해요", required = true, value = "제목")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ReviewDto content(String content) {
    this.content = content;
    return this;
  }

   /**
   * 본문
   * @return content
  **/
  @ApiModelProperty(example = "한 번 붙였다가 다시 붙이려고 하면, 접착이 안되요~", required = true, value = "본문")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public ReviewDto createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 최초 생성 시각
   * @return createdAt
  **/
  @ApiModelProperty(example = "2017-03-01T00:00:00+0900", value = "최초 생성 시각")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public ReviewDto updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 최종 수정 시각
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2017-03-01T00:00:00+0900", value = "최종 수정 시각")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ReviewDto author(UserDto author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @ApiModelProperty(value = "")
  public UserDto getAuthor() {
    return author;
  }

  public void setAuthor(UserDto author) {
    this.author = author;
  }

  public ReviewDto product(ProductDto product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @ApiModelProperty(value = "")
  public ProductDto getProduct() {
    return product;
  }

  public void setProduct(ProductDto product) {
    this.product = product;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReviewDto reviewDto = (ReviewDto) o;
    return Objects.equals(this.title, reviewDto.title) &&
        Objects.equals(this.content, reviewDto.content) &&
        Objects.equals(this.createdAt, reviewDto.createdAt) &&
        Objects.equals(this.updatedAt, reviewDto.updatedAt) &&
        Objects.equals(this.author, reviewDto.author) &&
        Objects.equals(this.product, reviewDto.product);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, content, createdAt, updatedAt, author, product);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReviewDto {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

