/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AccessToken model module.
* @module model/AccessToken
* @version 1
*/
export default class AccessToken {
    /**
    * Constructs a new <code>AccessToken</code>.
    * @alias module:model/AccessToken
    * @class
    * @param accessToken {String} 액세스 토큰
    * @param tokenType {module:model/AccessToken.TokenTypeEnum} 토큰 인증 스킴
    * @param expiresIn {Number} 만료까지 남은 시간
    */

    constructor(accessToken, tokenType, expiresIn) {
        

        
        

        this['access_token'] = accessToken;this['token_type'] = tokenType;this['expires_in'] = expiresIn;

        
    }

    /**
    * Constructs a <code>AccessToken</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AccessToken} obj Optional instance to populate.
    * @return {module:model/AccessToken} The populated <code>AccessToken</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccessToken();

            
            
            

            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('token_type')) {
                obj['token_type'] = ApiClient.convertToType(data['token_type'], 'String');
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
            }
        }
        return obj;
    }

    /**
    * 액세스 토큰
    * @member {String} access_token
    */
    access_token = undefined;
    /**
    * 토큰 인증 스킴
    * @member {module:model/AccessToken.TokenTypeEnum} token_type
    */
    token_type = undefined;
    /**
    * 만료까지 남은 시간
    * @member {Number} expires_in
    */
    expires_in = undefined;






    /**
    * Allowed values for the <code>token_type</code> property.
    * @enum {String}
    * @readonly
    */
    static TokenTypeEnum = {
    
        /**
         * value: "bearer"
         * @const
         */
        "bearer": "bearer"    
    };



}


