/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The NewProductRequest model module.
* @module model/NewProductRequest
* @version 1
*/
export default class NewProductRequest {
    /**
    * Constructs a new <code>NewProductRequest</code>.
    * @alias module:model/NewProductRequest
    * @class
    * @param title {String} 상품명
    * @param stock {Number} 재고수량
    * @param price {Number} 가격
    * @param description {String} 상품 설명
    */

    constructor(title, stock, price, description) {
        

        
        

        this['title'] = title;this['stock'] = stock;this['price'] = price;this['description'] = description;

        
    }

    /**
    * Constructs a <code>NewProductRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NewProductRequest} obj Optional instance to populate.
    * @return {module:model/NewProductRequest} The populated <code>NewProductRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewProductRequest();

            
            
            

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('stock')) {
                obj['stock'] = ApiClient.convertToType(data['stock'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * 상품명
    * @member {String} title
    */
    title = undefined;
    /**
    * 재고수량
    * @member {Number} stock
    */
    stock = undefined;
    /**
    * 가격
    * @member {Number} price
    */
    price = undefined;
    /**
    * 상품 설명
    * @member {String} description
    */
    description = undefined;








}


