/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Paginator model module.
* @module model/Paginator
* @version 1
*/
export default class Paginator {
    /**
    * Constructs a new <code>Paginator</code>.
    * @alias module:model/Paginator
    * @class
    * @param total {Number} 총 리소스 개수
    * @param count {Number} 현재 페이지에 표시된 리소스 개수
    * @param perPage {Number} 페이지당 리소스 표시 개수
    * @param currentPage {Number} 현재 페이지 번호
    * @param totalPages {Number} 총 페이지 수
    * @param links {Object} 
    */

    constructor(total, count, perPage, currentPage, totalPages, links) {
        

        
        

        this['total'] = total;this['count'] = count;this['per_page'] = perPage;this['current_page'] = currentPage;this['total_pages'] = totalPages;this['links'] = links;

        
    }

    /**
    * Constructs a <code>Paginator</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Paginator} obj Optional instance to populate.
    * @return {module:model/Paginator} The populated <code>Paginator</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Paginator();

            
            
            

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('per_page')) {
                obj['per_page'] = ApiClient.convertToType(data['per_page'], 'Number');
            }
            if (data.hasOwnProperty('current_page')) {
                obj['current_page'] = ApiClient.convertToType(data['current_page'], 'Number');
            }
            if (data.hasOwnProperty('total_pages')) {
                obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], Object);
            }
        }
        return obj;
    }

    /**
    * 총 리소스 개수
    * @member {Number} total
    */
    total = undefined;
    /**
    * 현재 페이지에 표시된 리소스 개수
    * @member {Number} count
    */
    count = undefined;
    /**
    * 페이지당 리소스 표시 개수
    * @member {Number} per_page
    */
    per_page = undefined;
    /**
    * 현재 페이지 번호
    * @member {Number} current_page
    */
    current_page = undefined;
    /**
    * 총 페이지 수
    * @member {Number} total_pages
    */
    total_pages = undefined;
    /**
    * @member {Object} links
    */
    links = undefined;








}


