/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NewProductRequest from './NewProductRequest';
import Timestamp from './Timestamp';





/**
* The ProductDto model module.
* @module model/ProductDto
* @version 1
*/
export default class ProductDto {
    /**
    * Constructs a new <code>ProductDto</code>.
    * @alias module:model/ProductDto
    * @class
    * @implements module:model/NewProductRequest
    * @implements module:model/Timestamp
    * @param title {String} 상품명
    * @param stock {Number} 재고수량
    * @param price {Number} 가격
    * @param description {String} 상품 설명
    */

    constructor(title, stock, price, description) {
        

        
        NewProductRequest.call(this, title, stock, price, description);Timestamp.call(this);

        

        
    }

    /**
    * Constructs a <code>ProductDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProductDto} obj Optional instance to populate.
    * @return {module:model/ProductDto} The populated <code>ProductDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductDto();

            
            
            NewProductRequest.constructFromObject(data, obj);Timestamp.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement NewProductRequest interface:
    /**
    * 상품명
    * @member {String} title
    */
    title = undefined;
/**
    * 재고수량
    * @member {Number} stock
    */
    stock = undefined;
/**
    * 가격
    * @member {Number} price
    */
    price = undefined;
/**
    * 상품 설명
    * @member {String} description
    */
    description = undefined;

    // Implement Timestamp interface:
    /**
    * 최초 생성 시각
    * @member {Date} created_at
    */
    created_at = undefined;
/**
    * 최종 수정 시각
    * @member {Date} updated_at
    */
    updated_at = undefined;







}


