/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ProductDto from './ProductDto';





/**
* The ProductListResponse model module.
* @module model/ProductListResponse
* @version 1
*/
export default class ProductListResponse {
    /**
    * Constructs a new <code>ProductListResponse</code>.
    * @alias module:model/ProductListResponse
    * @class
    * @param data {Array.<module:model/ProductDto>} 
    * @param meta {Object} 
    */

    constructor(data, meta) {
        

        
        

        this['data'] = data;this['meta'] = meta;

        
    }

    /**
    * Constructs a <code>ProductListResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProductListResponse} obj Optional instance to populate.
    * @return {module:model/ProductListResponse} The populated <code>ProductListResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductListResponse();

            
            
            

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ProductDto]);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/ProductDto>} data
    */
    data = undefined;
    /**
    * @member {Object} meta
    */
    meta = undefined;








}


