/**
 * DB-LOCK-POC
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NewUserRequest from './NewUserRequest';
import Timestamp from './Timestamp';





/**
* The UserDto model module.
* @module model/UserDto
* @version 1
*/
export default class UserDto {
    /**
    * Constructs a new <code>UserDto</code>.
    * @alias module:model/UserDto
    * @class
    * @implements module:model/NewUserRequest
    * @implements module:model/Timestamp
    * @param email {String} 사용자 이메일
    * @param password {String} 사용자 비밀번호 (6 글자 이상)
    */

    constructor(email, password) {
        

        
        NewUserRequest.call(this, email, password);Timestamp.call(this);

        

        
    }

    /**
    * Constructs a <code>UserDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserDto} obj Optional instance to populate.
    * @return {module:model/UserDto} The populated <code>UserDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDto();

            
            
            NewUserRequest.constructFromObject(data, obj);Timestamp.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * ID
    * @member {Number} id
    */
    id = undefined;


    // Implement NewUserRequest interface:
    /**
    * 사용자 이메일
    * @member {String} email
    */
    email = undefined;
/**
    * 사용자 비밀번호 (6 글자 이상)
    * @member {String} password
    */
    password = undefined;
/**
    * 사용자 이름
    * @member {String} name
    */
    name = undefined;

    // Implement Timestamp interface:
    /**
    * 최초 생성 시각
    * @member {String} created_at
    */
    created_at = undefined;
/**
    * 최종 수정 시각
    * @member {String} updated_at
    */
    updated_at = undefined;







}


