<?php
/**
 * AuthApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Appkr\SwaggerPocApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DB-LOCK-POC
 *
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Appkr\SwaggerPocApi;

use \Appkr\SwaggerPocApi\Configuration;
use \Appkr\SwaggerPocApi\ApiException;
use \Appkr\SwaggerPocApi\ObjectSerializer;

/**
 * AuthApiTest Class Doc Comment
 *
 * @category Class
 * @package  Appkr\SwaggerPocApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AuthApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for login
     *
     * 로그인합니다..
     *
     */
    public function testLogin()
    {
    }

    /**
     * Test case for logout
     *
     * 로그아웃합니다..
     *
     */
    public function testLogout()
    {
    }

    /**
     * Test case for me
     *
     * 프로필 정보를 확인합니다..
     *
     */
    public function testMe()
    {
    }

    /**
     * Test case for refreshToken
     *
     * 로그인합니다..
     *
     */
    public function testRefreshToken()
    {
    }
}
