<?php
/**
 * ProductApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Appkr\SwaggerPocApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DB-LOCK-POC
 *
 * 라라벨에 스웨거 적용 테스트를 위한 프로젝트
 *
 * OpenAPI spec version: 1
 * Contact: juwonkim@me.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Appkr\SwaggerPocApi;

use \Appkr\SwaggerPocApi\Configuration;
use \Appkr\SwaggerPocApi\ApiException;
use \Appkr\SwaggerPocApi\ObjectSerializer;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  Appkr\SwaggerPocApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createProduct
     *
     * 새 상품을 등록합니다..
     *
     */
    public function testCreateProduct()
    {
    }

    /**
     * Test case for deleteProduct
     *
     * 상품을 삭제합니다..
     *
     */
    public function testDeleteProduct()
    {
    }

    /**
     * Test case for listProducts
     *
     * 상품 목록을 조회합니다..
     *
     */
    public function testListProducts()
    {
    }

    /**
     * Test case for updateProduct
     *
     * 상품을 수정합니다..
     *
     */
    public function testUpdateProduct()
    {
    }
}
